config/routes.rb
Rails.application.routes.draw do
  scope module: :web do
    scope module: :public do
      # Home
      get '/', to: "home#index", as: :root
      post "register", to: "home#account_register", as: :account_register
      
      # Accounts
      get "login", to: "accounts#index", as: :account_login
      post "login", to: "accounts#login_submit", as: :account_login_submit
      get "logout", to: "accounts#logout_submit", as: :account_logout

      # Ranking
      get "ranking/players", to: "ranking#players", as: :ranking_players
      get "ranking/budokai_solo", to: "ranking#budokai_solo", as: :ranking_budokai_solo
      get "ranking/budokai_party", to: "ranking#budokai_party", as: :ranking_budokai_party
      get "ranking/guilds", to: "ranking#guilds", as: :ranking_guilds
    end

    scope module: :accounts do
      # Dashboard
      get '/dashboard', to: "dashboard#index", as: :dashboard

      # Settings
      get '/settings', to: "settings#index", as: :settings
      put '/settings/update_personal_informations', to: "settings#update_personal_informations", as: :settings_update_personal_informations
      get '/settings/change_password', to: "settings#change_password", as: :settings_change_password
      put '/settings/update_password', to: "settings#update_password", as: :settings_update_password
    end

    scope :admins, as: :admin, module: :admins do
      # Dashboard
      get '/', to: "dashboard#index", as: :dashboard
  
      # Accounts
      get '/accounts', to: "accounts#index", as: :accounts
      get '/accounts/:account_id/add_cash_points', to: "accounts#add_cash_points", as: :accounts_add_cash_points
      put '/accounts/:account_id/add_cash_points', to: "accounts#add_cash_points_submit", as: :accounts_add_cash_points_submit
      get '/accounts/:account_id/ban', to: "accounts#ban_form", as: :accounts_ban_form
      post '/accounts/:account_id/ban', to: "accounts#ban_form_submit", as: :accounts_ban_form_submit
  
      # Characters
      get '/characters', to: "characters#index", as: :characters

      # Download Links
      get '/download_links', to: "download_links#index", as: :download_links
      get '/download_links/new', to: "download_links#new", as: :download_links_new
      post '/download_links/create', to: "download_links#create", as: :download_links_create
      get '/download_links/:id/edit', to: "download_links#edit", as: :download_links_edit
      put '/download_links/:id/update', to: "download_links#update", as: :download_links_update
      delete '/download_links/:id/destroy', to: "download_links#destroy", as: :download_links_destroy
    end
  end
end

app/models/account.rb
class Account < DboAcc
  authenticates_with_sorcery!
  attr_reader :password

  self.primary_key = :AccountID
  attribute :isGm, ActiveModel::Type::Integer.new

  validates :email, length: {maximum: 80}
  validates :Username, presence: true, uniqueness: true, length: {maximum: 16}

  has_many :characters, foreign_key: :AccountID

  enum isGm: {
    player: 0,
    early_access: 6,
    community_manager: 7,
    team_leader: 8,
    game_master: 9,
    admin: 10
  }, _prefix: :isGm

  enum acc_status: {
    pending: 'pending',
    block: 'block',
    active: 'active'
  }

  def self.find_by_id(id)
    Account.find_by(AccountID: id)
  end

  def valid_password?(password)
    password.eql?(self.Password_hash)
  end

  def admin_level?
    admin? && isGm_admin?
  end

  def can_be_banned?
    active? && isGm_player?
  end
end

app/controllers/web/accounts/dashboard_controller.rb
module Web
  module Accounts
    class DashboardController < ApplicationController
      before_action :require_account

      def index
        @characters = current_user.characters
      end
    end
  end
end

app/controllers/web/accounts/settings_controller.rb
module Web
  module Accounts
    class SettingsController < ApplicationController
      before_action :require_account

      def index
        @personal_informations_form = Forms::Accounts::PersonalInformationForm.new
      end

      def update_personal_informations
        @personal_informations_form ||= personal_informations_form
        if @personal_informations_form.call
          redirect_to settings_path, notice: "Personal informations updated"
        else
          redirect_to settings_path, alert: @personal_informations_form.errors.full_messages.join("<br>")
        end
      end

      def change_password
        @change_password_form = Forms::Accounts::ChangePasswordForm.new
      end

      def update_password
        @change_password_form = change_password_form
        if @change_password_form.call
          redirect_to settings_change_password_path, notice: "Password updated"
        else
          redirect_to settings_change_password_path, alert: @change_password_form.errors.full_messages.join("<br>")
        end
      end

      private

      def personal_informations_form
        Forms::Accounts::PersonalInformationForm.new(personal_informations_form_params)
      end

      def personal_informations_form_params
        {
          email: params[:form][:email],
          password: params[:form][:password],
          account: current_user
        }
      end

      def change_password_form
        Forms::Accounts::ChangePasswordForm.new(change_password_form_params)
      end

      def change_password_form_params
        {
          account: current_user,
          current_password: params[:form][:current_password],
          password: params[:form][:password],
          password_confirmation: params[:form][:password_confirmation]
        }
      end
    end
  end
end

app/controllers/web/admins/accounts_controller.rb
module Web
  module Admins
    class AccountsController < BaseController
      before_action :load_account, only: [:add_cash_points, :ban_form]

      def index
        @accounts = query_accounts.accounts
      end

      def add_cash_points
        @add_cash_points_form = Forms::Admins::Accounts::AddCashPointsForm.new
      end

      def add_cash_points_submit
        @add_cash_points_form = Forms::Admins::Accounts::AddCashPointsForm.new(add_cash_points_params)

        if @add_cash_points_form.call
          redirect_to admin_accounts_path, notice: 'Cash points added successfully!'
        else
          redirect_to admin_accounts_add_cash_points_path, alert: @add_cash_points_form.errors.full_messages.join('<br>')
        end
      end

      def ban_form
        @ban_form = Forms::Admins::Accounts::BanForm.new
      end

      def ban_form_submit
        @ban_form = Forms::Admins::Accounts::BanForm.new(ban_form_params)

        if @ban_form.call
          redirect_to admin_accounts_path, notice: 'Account banned successfully!'
        else
          redirect_to admin_accounts_ban_path, alert: @ban_form.errors.full_messages.join('<br>')
        end
      end

      private

      def load_account
        @account = Account.find_by_id(params[:account_id])
      end

      def query_accounts
        @query_accounts ||= Query::Admins::Accounts.new(accounts_params)
      end

      def accounts_params
        prms = params.permit(:page, :per)

        prms.merge!(
          id: params[:search][:id],
          username: params[:search][:username],
          email: params[:search][:email],
          status: params[:search][:status],
          gm_level: params[:search][:gm_level],
        ) if params[:search].present?
        prms
      end

      def add_cash_points_params
        {
          account_id: pa[:account_id],
          cash_points: pa[:form][:cash_points],
          reason: pa[:form][:reason],
          admin: current_user
        }
      end

      def ban_form_params
        {
          account_id: pa[:account_id],
          permanent: pa[:form][:permanent],
          duration: pa[:form][:duration],
          reason: pa[:form][:reason],
          admin: current_user
        }
      end
    end
  end
end

app/views/web/accounts/settings/_navigation.html.erb
<% 
  current_page_classes = 'bg-sky-600 text-white'
  default_page_classes = 'bg-white-600 text-black border-sky-600'
%>

<div class="flex justify-center items-center pb-8">
  <%= link_to 'Personal Information',
              settings_path,
              class: "#{ current_page?(settings_path) ? current_page_classes : default_page_classes } inline-flex items-center rounded-md px-3 py-2 text-sm font-semibold shadow-sm border focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600" %>

  <%= link_to 'Change Password',
              settings_change_password_path,
              class: "#{ current_page?(settings_change_password_path) ? current_page_classes : default_page_classes } ml-6 inline-flex items-center rounded-md px-3 py-2 text-sm font-semibold shadow-sm border focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600" %>

</div>

app/views/web/accounts/settings/change_password.html.erb
<% title "Settings" %>

<div class="px-4 sm:px-6 lg:px-8">
  <div class="flow-root">
    <%= render 'navigation' %>

    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
          <%= form_for @change_password_form, as: :form, url: settings_update_password_path, html: { method: :put, class: 'space-y-6' } do |f| %>
            <div>
              <div class="flex items-center justify-between">
                <label htmlFor="password" class="block text-sm font-medium leading-6 text-gray-900">
                  Current Password
                </label>

              </div>
              <div class="mt-2">
                <%= f.password_field :current_password, class: 'block w-full outline-none rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', id: 'password', required: true, autocomplete: 'current-password' %>
              </div>
            </div>

            <div>
              <div class="flex items-center justify-between">
                <label htmlFor="password" class="block text-sm font-medium leading-6 text-gray-900">
                  New Password
                </label>

              </div>
              <div class="mt-2">
                <%= f.password_field :password, class: 'block w-full outline-none rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', id: 'password', required: true, autocomplete: 'current-password' %>
              </div>
            </div>

            <div>
              <div class="flex items-center justify-between">
                <label htmlFor="password" class="block text-sm font-medium leading-6 text-gray-900">
                  New Password Confirmation
                </label>

              </div>
              <div class="mt-2">
                <%= f.password_field :password_confirmation, class: 'block w-full outline-none rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', id: 'password', required: true, autocomplete: 'current-password' %>
              </div>
            </div>

            <div>
              <%= f.submit 'Update', class: 'flex w-full justify-center rounded-md bg-purple-600 px-3 py-1.5 text-sm font-semibold leading-6 cursor-pointer text-white shadow-sm hover:bg-purple-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-600' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/web/accounts/settings/index.html.erb
<% title "Settings" %>

<div class="px-4 sm:px-6 lg:px-8">
  <div class="flow-root">
    <%= render 'navigation' %>

    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
          <%= form_for @personal_informations_form, as: :form, url: settings_update_personal_informations_path, html: { method: :put, class: 'space-y-6' } do |f| %>

            <div>
              <label htmlFor="email" class="block text-sm font-medium leading-6 text-gray-900">
                Email address
              </label>
              <div class="mt-2">
                <%= f.text_field :email, class: 'block w-full outline-none rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', id: 'email', required: true, value: current_user.email %>
              </div>
            </div>

            <div>
              <div class="flex items-center justify-between">
                <label htmlFor="password" class="block text-sm font-medium leading-6 text-gray-900">
                  Password Confirmation
                </label>

              </div>
              <div class="mt-2">
                <%= f.password_field :password, class: 'block w-full outline-none rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:text-sm sm:leading-6', id: 'password', required: true, autocomplete: 'current-password' %>
              </div>
            </div>

            <div>
              <%= f.submit 'Update', class: 'flex w-full justify-center rounded-md bg-purple-600 px-3 py-1.5 text-sm font-semibold leading-6 cursor-pointer text-white shadow-sm hover:bg-purple-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-600' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>